name: CI

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
    - name: Say hello
      run: echo Hello, $USER
      env:
        USER: "test"
    - name: Greet ${{secrets.USER}}
      run: |
        echo Hello, ${{secrets.USER}}
        echo Hello, $USER
      env:
        USER: ${{secrets.USER}}
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
